version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'tailwindcss'
        versions: ['4.x']
      - dependency-name: 'eslint'
        versions: ['9.x']
      - dependency-name: 'tailwind-variants'
        versions: ['1.x']
    commit-message:
      prefix: 'build(deps)'
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      interval: 'weekly'
