version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(deps)'
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      interval: 'weekly'
